[package]
name = "logdog"
version = "0.1.1"
authors = ["Pierre Baillet <pierre@baillet.name>"]
edition = "2018"

[dependencies]

native-tls = "0.2.2"
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.3.0"
rand = "0.6.5"
regex = "1"

